// src/routes/notionclock/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { useSearchParams } from "runed/kit";
  import clockUpdate from "$lib/utils/clockUpdate.js";
  import { z } from "zod";

  const params = useSearchParams(
    z.object({
      bg: z.string().default("#191919"),
      bghex: z.string().default(""),
      text: z.string().default("#ffffff"),
      texthex: z.string().default(""),
      font: z.string().default("Poppins"),
      align: z.string().default("left"),
      format: z.string().default("DDD, ds MMM, yyyy"),
      time: z.string().default("H:mm P"),
      scale: z.coerce.number().default(1),
      padding: z.coerce.number().nullable().default(null),
      paddingTop: z.coerce.number().nullable().default(null),
      paddingBottom: z.coerce.number().nullable().default(null),
      paddingLeft: z.coerce.number().nullable().default(null),
      paddingRight: z.coerce.number().nullable().default(null),
      timePadding: z.coerce.number().nullable().default(null),
    })
  );

  // Now that we have defaults, we can use the params directly
  let format = $derived(params.format);
  let time = $derived(params.time);

  let paddingStyle = $derived.by(() => {
    const basePadding = params.padding !== null ? params.padding : 0.5;
    const top = params.paddingTop !== null ? params.paddingTop : basePadding;
    const bottom = params.paddingBottom !== null ? params.paddingBottom : basePadding;
    const left = params.paddingLeft !== null ? params.paddingLeft : basePadding;
    const right = params.paddingRight !== null ? params.paddingRight : basePadding;

    return `padding: ${top}rem ${right}rem ${bottom}rem ${left}rem;`;
  });

  let timePadding = $derived(params.timePadding !== null ? `padding: ${params.timePadding}rem;` : "");

  let align = $derived(params.align === "right" ? `text-align: right; justify-content: flex-end;` : params.align === "center" ? `text-align: center; justify-content: center;` : `text-align: left; justify-content: start;`);

  let textColor = $derived(params.texthex ? `#${params.texthex}` : params.text);
  let bgColor = $derived(params.bghex ? `#${params.bghex}` : params.bg);
  let fontParse: string = $derived(`font-family: "${params.font.replaceAll("_", " ")}";`);
  let clockScale = $derived(`font-size: ${params.scale}rem; line-height: ${params.scale}rem;`);
  let timeScale = $derived(`font-size: ${params.scale * 1.8}rem; line-height: ${params.scale * 1.8}rem;`);

  const frameStyle = $derived(`color: red; height: 100vh; background-color: ${bgColor};`);
  const clockStyle = $derived(`color: ${textColor}; ${fontParse} ${clockScale} ${paddingStyle} ${align}`);
  const timeStyle = $derived(`${timeScale} ${timePadding}`);
  const dateStyle = ``;

  // Debug URL parameters
  $inspect(params);
  $inspect(params.padding);
  $inspect(params.scale);

  let timeData = $state({ time: "", date: "" });
  let timer: NodeJS.Timeout | null = null;

  onMount(() => {
    timeData = clockUpdate(format, time);
    timer = setInterval(() => {
      timeData = clockUpdate(format, time);
    }, 1000);
  });

  onDestroy(() => {
    if (timer) {
      clearInterval(timer);
    }
  });
</script>

<div id="frame" style={frameStyle}>
  <div id="clock" style={clockStyle}>
    <span id="time" style={timeStyle}>
      {timeData.time}
    </span>
    <span id="date" style={dateStyle}>{timeData.date}</span>
  </div>
</div>

<style>
  :global(body) {
    margin: 0px !important;
    padding: 0px !important;
    overflow: hidden !important;
  }
  #clock {
    width: 100%;
    overflow: hidden;
    padding: 0.5rem;
    display: flex;
    text-align: left;
    justify-content: start;
    font-family: Poppins;
    flex-direction: column;
    color: white;
    line-height: 1rem;
  }
  #time {
    font-weight: bold;
    font-size: 1.8rem;
    line-height: 1.8rem;
  }
</style>

// src/projects/notionclock.jsx
import React from 'react';
import '../styles/globals.scss';

import clockUpdate from '../modules/projects/notionclock';

import { useQueryParams, StringParam, NumberParam } from 'use-query-params';

export default function NotionClock({ toggleNav }) {
  const [query] = useQueryParams({
    bg: StringParam,
    bghex: StringParam,
    text: StringParam,
    texthex: StringParam,
    font: StringParam,
    align: StringParam,
    format: StringParam,
    time: StringParam,
    scale: NumberParam,
    padding: NumberParam,
    paddingTop: NumberParam,
    paddingBottom: NumberParam,
    paddingLeft: NumberParam,
    paddingRight: NumberParam,
    timePadding: NumberParam
  });

  let timeStyle = {
    fontWeight: 'bold',
    fontSize: '1.8rem',
    lineHeight: '1.8rem',
  };

  let clockStyle = {
    width: '100%',
    overflow: 'hidden',
    padding: '0.5rem',
    display: 'flex',
    textAlign: 'left',
    justifyContent: 'start',
    fontFamily: 'Poppins',
    flexDirection: 'column',
    color: 'white',
    lineHeight: '1rem',
  };

  // 24 Hour clock
  let formatCode,
    formatTime = '';

  function styleUpdate(clock, frame, timeText) {
    if (query.bg) frame.style.backgroundColor = query.bg;
    if (query.bghex) frame.style.backgroundColor = `#${query.bghex}`;
    if (query.text) clock.style.color = query.text;
    if (query.texthex) clock.style.color = `#${query.texthex}`;
    if (query.font) clock.style.fontFamily = query.font.replaceAll('_', ' ');
    if (query.format) formatCode = query.format;
    if (query.time) formatTime = query.time;
    if (query.scale) {
      clock.style.fontSize = `${query.scale}rem`;
      clock.style.lineHeight = `${query.scale}rem`;
      timeText.style.fontSize = `${query.scale * 1.8}rem`;
      timeText.style.lineHeight = `${query.scale * 1.8}rem`;
    }
    if (query.align === 'right') {
      clock.style.textAlign = 'right';
      clock.style.justifyContent = 'flex-end';
    }
    if (query.align === 'center') {
      clock.style.textAlign = 'center';
      clock.style.justifyContent = 'center';
    }
    if (query.padding) clock.style.padding = `${query.padding}px`;
    if (query.paddingTop) clock.style.paddingTop = `${query.paddingTop}px`;
    if (query.paddingBottom) clock.style.paddingBottom = `${query.paddingBottom}px`;
    if (query.paddingLeft) clock.style.paddingLeft = `${query.paddingLeft}px`;
    if (query.paddingRight) clock.style.paddingRight = `${query.paddingRight}px`;
    if (query.timePadding) timeText.style.padding = `${query.timePadding}px`;
  }

  let [time, timeReset] = React.useState({ time: '', date: '' });

  React.useEffect(() => {
    toggleNav(false);
    let clock = document.getElementById('clock');
    let frame = document.getElementById('frame');
    let timeText = document.getElementById('time');
    styleUpdate(clock, frame, timeText);
    const timer = setTimeout(() => {
      timeReset(clockUpdate(formatCode, formatTime));
    }, 1000);
    return () => clearTimeout(timer);
  });

  return (
    <div id="frame" style={{ height: '100vh', backgroundColor: '#2f3437' }}>
      <div id="clock" style={clockStyle}>
        <span id="time" style={timeStyle}>
          {time.time}
        </span>
        <span id="date">{time.date}</span>
      </div>
    </div>
  );
}
